### ISSUE TITLE
opentracing WARN with jms.tracing=opentracing

### ISSUE THREAD

**Issue by 15I** [amqphub/quarkus-qpid-jms#1]
application.properties:

connection.uri = failover:(amqp://${messaging.service.host}:${messaging.service.port})?jms.tracing=opentracing&amqp.saslMechanisms=ANONYMOUS

terminal log:

2019-11-14 01:59:23,845 WARN  [org.apa.qpi.jms.uti.QpidJMSThreadFactory] (JmsSession [ID:0a2bd489-e8ba-4b01-8bc2-e9be717e5a10:1:1] delivery dispatcher) Thread: JmsSession [ID:0a2bd489-e8ba-4b01-8bc2-e9be717e5a10:1:1] delivery dispatcher failed due to an uncaught exception: io.opentracing.Tracer$SpanBuilder.withTag(Lio/opentracing/tag/Tag;Ljava/lang/Object;)Lio/opentracing/Tracer$SpanBuilder;

**Comment by gemmellr** [comment]
If you turn up the logging to TRACE it should also output the full stacktrace which might better convey the original issue. Some detail on versions in use, which particular OpenTracing tracer implementation you are using etc would be useful also.

**Comment by 15I** [comment]
Quarkus 1.0.1.Final
Quarkus extensions: 
  quarkus-smallrye-opentracing
  quarkus-qpid-jms (Version 0.8.2)

Quarkus Installed features: [cdi, jaeger, qpid-jms, resteasy, smallrye-opentracing]

Terminal Log:
....
2019-12-01 11:42:48,140 WARN  [org.apa.qpi.jms.uti.QpidJMSThreadFactory] (JmsSession [ID:22d9cded-4397-46ba-a73b-6812f8d61634:1:1] delivery dispatcher) Thread: JmsSession [ID:22d9cded-4397-46ba-a73b-6812f8d61634:1:1] delivery dispatcher failed due to an uncaught exception: io.opentracing.Tracer$SpanBuilder.withTag(Lio/opentracing/tag/Tag;Ljava/lang/Object;)Lio/opentracing/Tracer$SpanBuilder;
2019-12-01 11:42:48,140 TRACE [org.apa.qpi.jms.uti.QpidJMSThreadFactory] (JmsSession [ID:22d9cded-4397-46ba-a73b-6812f8d61634:1:1] delivery dispatcher) Uncaught Stacktrace: : java.lang.NoSuchMethodError: io.opentracing.Tracer$SpanBuilder.withTag(Lio/opentracing/tag/Tag;Ljava/lang/Object;)Lio/opentracing/Tracer$SpanBuilder;
        at org.apache.qpid.jms.tracing.opentracing.OpenTracingTracer.asyncDeliveryInit(OpenTracingTracer.java:157)
        at org.apache.qpid.jms.JmsMessageConsumer.deliverNextPending(JmsMessageConsumer.java:774)
        at org.apache.qpid.jms.JmsMessageConsumer.access$100(JmsMessageConsumer.java:61)
        at org.apache.qpid.jms.JmsMessageConsumer$MessageDeliverTask.run(JmsMessageConsumer.java:840)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.qpid.jms.util.QpidJMSThreadFactory$1.run(QpidJMSThreadFactory.java:86)
        at java.lang.Thread.run(Thread.java:748)
...

**Comment by gemmellr** [comment]
The support for tracing in Qpid JMS is built against OpenTracing API 0.33.0 and also works with 0.32.0, while it seems your setup is providing 0.31.0 and the older version it isnt compatible due to changes made in the later releases which added and removed APIs.

I'd suggest raising an update request for the other components.
